version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: ./containers/main/Dockerfile
    #container_name: main-container
    volumes:
      # bind vscode workspace root path to container target
      - type: bind
        source: ../
        target: /workspace
        # consistency: cached # (optional) for performance
        
    command: tail -f /dev/null # keep the container running
